FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
COPY --from=build target/chat-1.jar chat-1.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "chat-1.jar"]


